name = "aigw"
compatibility_date = "2023-01-01"
main = "src/index.ts"
node_compat = true

keep_vars = true

[vars]
ENVIRONMENT = 'dev'
CUSTOM_HEADERS_TO_IGNORE = []
#
#Configuration for DEVELOPMENT environment
#
[env.staging]
name = "aigw-dev"

[env.staging.vars]
ENVIRONMENT = 'staging'
CUSTOM_HEADERS_TO_IGNORE = []


#
#Configuration for PRODUCTION environment
#
[env.production]
name = "aigw"
logpush=true

[env.production.vars]
ENVIRONMENT = 'production'
CUSTOM_HEADERS_TO_IGNORE = []
