name: Deploy

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy AIGateway
    steps:
      - uses: actions/checkout@v4
      - name: AIGateway
        uses: cloudflare/wrangler-action@v3
        with:
          packageManager: npm
          name: aigateway
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}